name: raskara_boutique
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  csv: ^6.0.0
  provider: ^6.1.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  path_provider: ^2.1.5
  flutter_stripe: ^11.4.0
  shared_preferences: ^2.5.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  sqflite: ^2.4.1
  http: ^1.3.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/nav_transaction.svg
    - assets/images/nav_history.svg
    - assets/images/nav_home.svg
    - assets/images/plus.svg
    - assets/images/minus.svg
    - assets/images/cart.svg
    - assets/images/placeholder.png

    - assets/payment/bca.png
    - assets/payment/bni.png
    - assets/payment/briva.png
    - assets/payment/dana.png
    - assets/payment/gopay.png
    - assets/payment/qris.png
    - assets/payment/shopepay.png

