// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYWr8FVzr54LkVe4-fg3-XU1vUuq9lY_4',
    appId: '1:1052369246355:web:2f77e317cc5dae8ad09566',
    messagingSenderId: '1052369246355',
    projectId: 'raskaraboutique',
    authDomain: 'raskaraboutique.firebaseapp.com',
    storageBucket: 'raskaraboutique.firebasestorage.app',
    measurementId: 'G-Y983HBY0MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ijMu79jSpmwLrqqEZHpuOgjquIVT53M',
    appId: '1:1052369246355:android:fc794ba222136ae6d09566',
    messagingSenderId: '1052369246355',
    projectId: 'raskaraboutique',
    storageBucket: 'raskaraboutique.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKUuuE3DzO7xVqqNZL0wHHyfJNmPm8t2g',
    appId: '1:1052369246355:ios:60401ca8723dee72d09566',
    messagingSenderId: '1052369246355',
    projectId: 'raskaraboutique',
    storageBucket: 'raskaraboutique.firebasestorage.app',
    iosBundleId: 'com.example.raskaraBoutique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKUuuE3DzO7xVqqNZL0wHHyfJNmPm8t2g',
    appId: '1:1052369246355:ios:60401ca8723dee72d09566',
    messagingSenderId: '1052369246355',
    projectId: 'raskaraboutique',
    storageBucket: 'raskaraboutique.firebasestorage.app',
    iosBundleId: 'com.example.raskaraBoutique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYWr8FVzr54LkVe4-fg3-XU1vUuq9lY_4',
    appId: '1:1052369246355:web:5d6d18180f079587d09566',
    messagingSenderId: '1052369246355',
    projectId: 'raskaraboutique',
    authDomain: 'raskaraboutique.firebaseapp.com',
    storageBucket: 'raskaraboutique.firebasestorage.app',
    measurementId: 'G-YRGNQHKS33',
  );
}
